apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      serviceAccountName: todo-app-sa
      containers:
        - name: todo-app
          image: europe-west4-docker.pkg.dev/wide-net-466915-c6/todo-nest-app-repo/todo-app:latest
          envFrom:
            - configMapRef:
                name: todo-config
            - secretRef:
                name: todo-secret
          resources:
            limits:
              cpu: "1"
              memory: "1024Mi"
            requests:
              cpu: "500m"
              memory: "512Mi"

          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: api/liveliness/health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: api/liveliness/health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
